const zhCN = {
  brand: '墨笺 Markdown',
  title: '墨笺 Markdown｜写下来，读进去，留下批注',
  description: '免安装，在浏览器中编辑 Markdown、实时预览和划线批注。墨笺提供本地缓存与导出，也可通过本地版连接文件和可选 AI 助手。',
  language: '语言',
  open: '打开编辑器',
  eyebrow: '写作 · 阅读 · 批注',
  lead: '让文字落笔，让思考留下。',
  tryBrowser: '在浏览器中试用',
  source: '查看源码',
  browserNote: '无需安装即可编辑、阅读和批注。内容缓存在当前浏览器中，请导出备份。',
  workflow: '从一段文字，到自己的理解',
  editTitle: '边写边读',
  editBody: '在源码区编辑 Markdown，在只读预览中查看排版。双击即可在原文与预览之间定位。',
  annotateTitle: '留下思考',
  annotateBody: '选中文字，高亮、划线或写下批注，把值得回看的想法留在段落旁。',
  saveTitle: '带走你的文字',
  saveBody: '导入与导出 Markdown，或把预览保存成长图。浏览器缓存可能被清除，请另存重要内容。',
  editions: '从浏览器开始，按需走向本地',
  browserTitle: '浏览器体验版',
  browserBody: '打开即用，支持编辑、只读预览、批注、本地缓存和导入导出。',
  localTitle: '本地版与桌面端',
  localBody: '本地 Agent Bridge 提供最近阅读与本地文件双向同步。可从源码运行，桌面端还提供原生文件对话框。',
  desktopTitle: '桌面端目前提供测试安装包',
  desktopBody: 'macOS 与 Windows 安装包用于测试，并非正式签名发布。CI 冒烟测试不代表完整安装验证，也不代表已通过 Gatekeeper 或 SmartScreen 检查。',
  aiTitle: 'AI 助手，按需配置',
  aiBody: '需在本地安装并登录 Claude Code 或 Codex CLI，或配置 Gemini API 密钥。服务商可能收费；安装桌面端后仍需完成 AI 配置。',
  license: '源码开放 · PolyForm Noncommercial 1.0.0',
  footer: '为阅读、学习与自己的思考留一页。',
  previewLabel: '阅读与批注示意',
  sampleHeading: '给一个好想法留点空间',
  sampleBody: '慢一点读，写下问题。让一段文字，成为下一次思考的起点。',
  sampleNote: '这个想法，值得回来看。',
  desktopLink: '查看桌面测试说明',
  docsLink: '安装与使用文档',
};

type LandingCopy = { [Key in keyof typeof zhCN]: string };

export const landingCopy: Record<string, LandingCopy> = {
  'zh-CN': zhCN,
  'zh-TW': {
    brand: '墨笺 Markdown',
    title: '墨笺 Markdown｜寫下文字，讀出想法，留下註記',
    description: '免安裝，在瀏覽器中編輯 Markdown、即時預覽並標記重點。墨笺提供本機快取與匯出，也可透過本機版連接檔案和選用 AI 助理。',
    language: '語言',
    open: '開啟編輯器',
    eyebrow: '寫作 · 閱讀 · 註記',
    lead: '寫下文字，留下思考。',
    tryBrowser: '在瀏覽器中試用',
    source: '查看原始碼',
    browserNote: '不必安裝，即可編輯、閱讀與註記。內容快取於目前的瀏覽器，請匯出備份。',
    workflow: '從一段文字，到自己的理解',
    editTitle: '邊寫邊讀',
    editBody: '在原始碼區編輯 Markdown，在唯讀預覽中查看排版。按兩下即可在原文與預覽之間定位。',
    annotateTitle: '留下思考',
    annotateBody: '選取文字，標記重點、畫線或寫下註記，把值得重讀的想法留在段落旁。',
    saveTitle: '帶走你的文字',
    saveBody: '匯入與匯出 Markdown，或將預覽儲存為長圖。瀏覽器快取可能遭到清除，請另存重要內容。',
    editions: '從瀏覽器開始，依需要使用本機版',
    browserTitle: '瀏覽器體驗版',
    browserBody: '開啟即用，支援編輯、唯讀預覽、註記、本機快取與匯入匯出。',
    localTitle: '本機版與桌面版',
    localBody: '本機 Agent Bridge 提供最近閱讀與本機檔案雙向同步。可從原始碼執行，桌面版另提供原生檔案對話框。',
    desktopTitle: '桌面版目前提供測試安裝程式',
    desktopBody: 'macOS 與 Windows 安裝程式供測試使用，並非正式簽署的發行版。CI 冒煙測試不代表完整安裝驗證，也不代表已通過 Gatekeeper 或 SmartScreen 檢查。',
    aiTitle: '依需要設定 AI 助理',
    aiBody: '需在本機安裝並登入 Claude Code 或 Codex CLI，或設定 Gemini API 金鑰。服務供應商可能收費；安裝桌面版後仍需完成 AI 設定。',
    license: '原始碼公開 · PolyForm Noncommercial 1.0.0',
    footer: '為閱讀、學習與自己的思考留一頁。',
    previewLabel: '閱讀與註記示意',
    sampleHeading: '為一個好想法留點空間',
    sampleBody: '慢一點讀，寫下問題。讓一段文字，成為下一次思考的起點。',
    sampleNote: '這個想法，值得再讀一次。',
    desktopLink: '查看桌面版測試說明',
    docsLink: '安裝與使用文件',
  },
  en: {
    brand: 'Mojian Markdown',
    title: 'Mojian Markdown | Write, read, annotate',
    description: 'Edit Markdown, preview your writing, and annotate in your browser. No install needed. Export your work, or explore local files and optional AI with the local edition.',
    language: 'Language',
    open: 'Open editor',
    eyebrow: 'WRITE · READ · ANNOTATE',
    lead: 'A quiet space for words and ideas.',
    tryBrowser: 'Try in your browser',
    source: 'View source',
    browserNote: 'Start writing, reading, and annotating without installing anything. Work is cached in this browser; export a backup.',
    workflow: 'From a passage to a thought of your own',
    editTitle: 'Write and read',
    editBody: 'Edit Markdown in the source pane and see it in a read-only preview. Double-click to jump between matching passages.',
    annotateTitle: 'Keep a thought',
    annotateBody: 'Highlight a passage, underline a phrase, or leave a note beside an idea worth revisiting.',
    saveTitle: 'Take your work with you',
    saveBody: 'Import and export Markdown, or save a preview as a long image. Browser caches can be cleared, so export important work.',
    editions: 'Start in your browser. Go local when you need to.',
    browserTitle: 'Browser edition',
    browserBody: 'Open and start editing, reading, and annotating, with browser caching, import, and export.',
    localTitle: 'Local and desktop editions',
    localBody: 'A local Agent Bridge adds recent documents and two-way local file sync. Run from source, or use the desktop app with native file dialogs.',
    desktopTitle: 'Desktop installers are test builds',
    desktopBody: 'macOS and Windows installers are for testing, not a formally signed release. CI smoke tests do not establish full installation coverage, Gatekeeper approval, or SmartScreen reputation.',
    aiTitle: 'Optional AI, with your own setup',
    aiBody: 'Install and sign in to Claude Code or Codex CLI locally, or configure a Gemini API key. Provider charges may apply. The desktop app still requires this AI setup.',
    license: 'Source available · PolyForm Noncommercial 1.0.0',
    footer: 'A page for reading, learning, and thinking for yourself.',
    previewLabel: 'Reading and annotation illustration',
    sampleHeading: 'Make room for a good idea',
    sampleBody: 'Read slowly. Write down a question. Let one passage become the start of your next thought.',
    sampleNote: 'An idea worth coming back to.',
    desktopLink: 'Read about desktop test builds',
    docsLink: 'Setup and documentation',
  },
  ja: {
    brand: '墨笺 Mojian',
    title: '墨笺 Mojian｜Markdownを書いて、読んで、注釈を残す',
    description: 'インストール不要。ブラウザーで Markdown を編集し、プレビューや注釈を活用できます。書き出しに加え、ローカル版ではファイル連携や任意の AI 設定にも対応。',
    language: '言語',
    open: 'エディターを開く',
    eyebrow: '書く · 読む · 注釈を残す',
    lead: '言葉と考えを、ゆっくり育てる。',
    tryBrowser: 'ブラウザーで試す',
    source: 'ソースコードを見る',
    browserNote: 'インストールせずに編集・閲覧・注釈を始められます。内容はこのブラウザーにキャッシュされるため、書き出してバックアップしてください。',
    workflow: '一節を読む。自分の考えが生まれる。',
    editTitle: '書きながら読む',
    editBody: 'ソース欄で Markdown を編集し、読み取り専用のプレビューで確認。ダブルクリックで対応する箇所へ移動できます。',
    annotateTitle: '考えを残す',
    annotateBody: '気になる一節をハイライトし、下線や注釈を追加。読み返したい考えを文章のそばに残せます。',
    saveTitle: '文章を持ち出す',
    saveBody: 'Markdown の読み込み・書き出しや、プレビューの縦長画像保存に対応。ブラウザーのキャッシュは消える場合があるため、大切な内容は書き出してください。',
    editions: 'まずはブラウザーで。必要に応じてローカルへ。',
    browserTitle: 'ブラウザー版',
    browserBody: '開いてすぐに編集・閲覧・注釈を利用できます。ブラウザー内のキャッシュと読み込み・書き出しに対応。',
    localTitle: 'ローカル版・デスクトップ版',
    localBody: 'ローカルの Agent Bridge で最近読んだ文書とローカルファイルの双方向同期を利用できます。ソースから実行でき、デスクトップ版では標準のファイル選択画面も使えます。',
    desktopTitle: 'デスクトップ版はテスト用ビルドです',
    desktopBody: 'macOS・Windows 向けインストーラーはテスト用で、正式に署名されたリリースではありません。CI のスモークテストは、インストール全体の検証や Gatekeeper・SmartScreen の承認を示すものではありません。',
    aiTitle: 'AI は必要に応じて設定',
    aiBody: 'Claude Code または Codex CLI をローカルにインストールしてログインするか、Gemini API キーを設定してください。提供元の料金が発生する場合があります。デスクトップ版のインストール後も AI の設定が必要です。',
    license: 'ソースコード公開 · PolyForm Noncommercial 1.0.0',
    footer: '読むこと、学ぶこと、自分で考えることのために。',
    previewLabel: '閲覧と注釈のイメージ',
    sampleHeading: 'ひとつの考えに、余白を',
    sampleBody: 'ゆっくり読んで、問いを書き留める。その一節が、次の考えの出発点になる。',
    sampleNote: 'あとでもう一度、考えたい。',
    desktopLink: 'デスクトップ版のテストについて',
    docsLink: 'セットアップとドキュメント',
  },
};
